### PR TITLE
Adding Debian Jessie systemd support

### PR DESCRIPTION
**Pull request by 0x9090**

### CODE REVIEW

**Comment by jsok** [comment]
Cool, since this is technically adding Debian support (previously Ubuntu was assumed), could you add some specs for when:

```
let(:facts) { {
  :osfamily => "Debian",
  : operatingsystem => "Debian",
  :operatingsystemmajrelease => 8,
} }
```

**Comment by 0x9090** [comment]
Isn't that what it's doing already?

**Comment by 0x9090** [comment]
Updated to add more robust Debian OS checking

**Comment by jsok** [comment]
Sorry, by specs I mean tests, see https://github.com/jsok/puppet-vault/blob/master/spec/classes/vault_spec.rb.

**Comment by jsok** [comment]
Hi @0x9090,
I'd still encourage you to add the necessary specs and reopen the PR, however I'm going to close this PR as it's had no activity for quite some time. As a principle I'm not willing to add untested functionality to this module.
Thanks!

**Pull request closed without merging**
