### PR TITLE
replace json func with to_json_pretty from stdlib

### PR DESCRIPTION
**Pull request by bastelfreak**
##### SUMMARY

stdlib has a nice function since 4.24.0 that can render a Puppet hash to pretty JSON. I think getting rid of a custom implemention is always a good approach. Also this allows us to create the config in a more readable way. Let me know if you're interested in this change. If so, I will update the spec tests. They currently fail because the new JSON structure has a bunch of \n

### CODE REVIEW

**Comment by jsok** [comment]
Great idea, I noticed this a while back too.

Pity about the tests, I'd really like to move away from asserting JSON against raw strings and look at integrating something like https://relishapp.com/waterlink/rspec-json-expectations/docs/json-expectations/include-json-matcher .

**Comment by bastelfreak** [comment]
My idea was to include a json file as fixtures and match the content against it.

**Comment by jsok** [comment]
@bastelfreak I've created https://github.com/jsok/puppet-vault/pull/118 to use JSON matchers. This might make your PR easier to merge.

**Comment by bastelfreak** [comment]
@jsok I rebased against your feature branch. This PR is now green \o/

**Comment by bastelfreak** [comment]
ok, I need to correct myself. they were green locally. I investigate

**Comment by bastelfreak** [comment]
@jsok this is now green. Could you merge your PR and afterwars this one?

**Pull request merged**
