### PR TITLE
Improve config output by prettifying JSON

### PR DESCRIPTION
**Pull request by BogdanSorlea**
Reading config files that have all whitespaces stripped (or like in this case - not
generated) can be difficult, hence I am hereby exploding the JSON to improve its
readability.

### CODE REVIEW

**Comment by BogdanSorlea** [comment]
@jsok - I don't think I have time nor immediate knowledge to fix the tests, so if you feel this is a good change feel free to fetch the changes and fix the changes yourself.

Thanks.

**Comment by jsok** [comment]
Thanks for the PR however at this stage I don't think pretty JSON output warrants adding another dependency to this module.

**Comment by BogdanSorlea** [comment]
I noticed you're not using module dependencies and I'm wondering why that is the case.

**Comment by jsok** [comment]
Can you elaborate? Are you referring to the dependencies in [`metadata.json`](https://github.com/jsok/puppet-vault/blob/master/metadata.json) ?

**Pull request closed without merging**
