### PR TITLE
Add support for raft storage

### PR DESCRIPTION
**Pull request by rgevaert**
This adds support for the raft storage backend

### CODE REVIEW

**Review by jsok — CHANGES_REQUESTED** [review]
Change looks good but the README and documentation should be updated before this is mergeable.

**Comment by rgevaert** [comment]
Ok, I would add a section about managing the storage (file/raft). OK?

**Comment by rgevaert** [comment]
@jsok done as requested

**Review by jsok — APPROVED** [review]
Thanks for making the requested changes

**Pull request merged**
